apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: My API description
spec:
  type: openapi
  lifecycle: production
  owner: team-name
  definition: |
    $ref: https://raw.githubusercontent.com/readmeio/oas-examples/refs/heads/main/3.0/json/petstore.json