apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: My API description
spec:
  type: openapi
  lifecycle: production
  owner: team-name
  definition: |
    $ref: https://rackerlabs.github.io/wadl2swagger/openstack/swagger/identity.json